[env]
TERM = "screen-256color"

[font]
size = 15

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.97
decorations = "none"
dynamic_padding = true

[window.padding]
x = 10
y = 10

[terminal.shell]
# program = "tmux"
# args = ["a"]
program = "sh"
args = ["-c", "tmux attach || tmux new -s 'HOME'"]

[colors.normal]
black = '#000000' 
red = '#F38BA8' 
green = '#f3faf0' 
yellow = '#ebeb1e'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
