#!/usr/bin/env bash

# A rebuild script that commits on a successful build (optionally)
set -e

# Usage: ./rebuild.sh [--verbose]

VERBOSE=false

# Check if user passed --verbose
if [[ "$1" == "--verbose" ]]; then
    VERBOSE=true
fi

# Edit your config
nvim /home/veer/dotfiles/nixos/configuration.nix

# cd to your config dir
pushd /home/veer/dotfiles/nixos > /dev/null

# Early return if no changes were detected
if git diff --quiet '*.nix'; then
    echo "No changes detected, exiting."
    popd > /dev/null
    exit 0
fi

# Show your changes
git diff -U0 '*.nix'

echo "NixOS Rebuilding..."

# Rebuild logic
if $VERBOSE; then
    sudo nixos-rebuild switch -I nixos-config=/home/veer/dotfiles/nixos/configuration.nix
else
    sudo nixos-rebuild switch -I nixos-config=/home/veer/dotfiles/nixos/configuration.nix &>nixos-switch.log \
        || (grep --color error nixos-switch.log && exit 1)
fi

# Get current generation metadata
current=$(nixos-rebuild list-generations | grep current)

# Ask for a commit message
echo
read -rp "Enter a commit message (leave empty to skip committing): " commit_msg

if [[ -n "$commit_msg" ]]; then
    git commit -am "$commit_msg"
    echo "✅ Changes committed."
else
    echo "ℹ️  No commit message entered. Skipping commit."
fi

# Back to where you were
popd > /dev/null

# Notify all OK!
notify-send -e "NixOS Rebuilt OK!" --icon=software-update-available

