#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
    echo "usage: open <file|url> [...]" >&2
    exit 1
fi

for target in "$@"; do
    err=$(xdg-open "$target" 2>&1 >/dev/null)
    [[ -n "$err" ]] && echo "open: $target: $err" >&2
done &

disown
