# Playback speed
] add speed 0.2
[ add speed -0.2
# BACKSPACE set speed 1.0         # reset speed

# Pause / Play
SPACE cycle pause
p cycle pause                   # also use 'p' for pause
k cycle pause                   # also use 'p' for pause

# Volume control
UP add volume 5
DOWN add volume -5
m cycle mute

# Seek
l seek 10
j seek -10
LEFT seek -5
RIGHT seek 5
SHIFT+LEFT seek -60
SHIFT+RIGHT seek 60

# Playlist navigation
> playlist-next force
< playlist-prev force

# Fullscreen
f cycle fullscreen

# Subtitles
v cycle sub-visibility
z add sub-delay -0.1
x add sub-delay 0.1
r cycle sub
t cycle sub-ass

# Audio track
# (useful for dual audio anime)
# Cycle audio tracks
a cycle audio

# Screenshots
s screenshot
S screenshot video

# Misc
i script-binding stats/display-stats  # toggle stats overlay

