# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace

general {
  ignore_empty_input = false
}

animations {
   enabled = true
}

auth { 
  fingerprint:enabled = true
  fingerprint:ready_message = "Scan yo finger twin"
}

background {
  monitor =
  path = screenshot
  # path = ~/wallpapers/valley-water.jpg
  blur_passes = 3
  brightness = .5
}

input-field {
  monitor = 
  size = 200, 50
  position = 0, -50
  outline_thickness = 6
  dots_size = 0.4
  fade_on_empty = false
  hide_input = false
  fail_text = NAH
}

# battery percentage
label {
  text = cmd[update:1000] echo "$(cat /sys/class/power_supply/BAT*/capacity)"%
  position = 600, 200
  halign = center
  valign = center
  font_family = monospace
  font_size = 20
  color = rgba(ffffffee)        
  shadow_color = rgba(000000ff)      
}

# battery status
label {
  monitor =
  text = cmd[update:1000] cat /sys/class/power_supply/BAT*/status
  position = 600, 160
  halign = center
  valign = center
  font_family = monospace
  font_size = 16
  color = rgba(ffffffee)        
  shadow_color = rgba(000000ff)      
}

# clock
label {
  monitor =
  text = $TIME12
  position = -700, 400            
  halign = center
  valign = center
  font_family = monospace
  font_size = 20
  color = rgba(ffffffee)        
  shadow_color = rgba(000000ff)      
}

# user veer
label {
  monitor =
  text = $USER
  position = 0, 20            
  halign = center
  valign = center
  font_family = monospace
  font_size = 20
  color = rgba(ffffffee)        
  shadow_color = rgba(000000ff)      
}

# login prompt
label {
  monitor = 
  text = log in twin 💝
  position = 0, 20
  valign = bottom
  halign = center
  font_family = monospace
  font_size = 16
  color = rgba(ffffff88)
  shadow_color = rgba(000000ff)      
}
