background {
    monitor =
    path = /home/veer/wallpapers/meme.jpg
    blur_passes = 1              
    brightness = 0.5             
}

input-field {
    monitor = 
    size = 200, 50
    position = 0, -50              
    halign = center
    valign = center
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    fade_on_empty = true
    hide_input = false
}

general {
    ignore_empty_input = false
}


label {
    monitor =
    text = $USER
    position = 0, 20            
    halign = center
    valign = center
    font_family = monospace
    font_size = 20
    color = rgba(ffffffee)        
    shadow_color = rgba(000000ff)      
}

label {
  monitor = 
  text = log in twin 💝
  position = 0, 20
  valign = bottom
  halight = center
  font_family = monospace
  font_size = 16
  color = rgba(ffffffee)
    shadow_color = rgba(000000ff)      
}
