general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 3
}

# dim screen
listener {
    timeout = 500 
    on-timeout = brightnessctl -s set 5
    on-resume = brightnessctl -r
}

# lock session
listener {
    timeout = 400
    on-timeout = loginctl lock-session
}

# turn screen off
listener {
    timeout = 500
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# suspend
listener {
    timeout = 600 
    on-timeout = systemctl suspend
}

