preload = /home/veer/wallpapers/artsy-sky.png
preload = /home/veer/wallpapers/city.png
preload = /home/veer/wallpapers/dark-flowers.png
preload = /home/veer/wallpapers/flowers.png
preload = /home/veer/wallpapers/library.png
preload = /home/veer/wallpapers/something--greek.png
preload = /home/veer/wallpapers/white.png
preload = /home/veer/wallpapers/woman.png
preload = /home/veer/wallpapers/something.jpg

wallpaper = ,/home/veer/wallpapers/something.jpg
