hl.monitor({ output = "eDP-1", mode = "2256x1504@60", position = "1779x1080", scale = 1.3 })
hl.monitor({ output = "DP-2", mode = "1920x1080@60", position = "1693x0", scale = 1 })

hl.workspace_rule({ workspace = "name:5", monitor = "eDP-1", default = true })
hl.workspace_rule({ workspace = "name:6", monitor = "eDP-1" })
hl.workspace_rule({ workspace = "name:1", monitor = "DP-2", default = true })
hl.workspace_rule({ workspace = "name:2", monitor = "DP-2" })
hl.workspace_rule({ workspace = "name:3", monitor = "DP-2" })
hl.workspace_rule({ workspace = "name:4", monitor = "DP-2" })
hl.workspace_rule({ workspace = "name:7", monitor = "DP-2" })
hl.workspace_rule({ workspace = "name:8", monitor = "DP-2" })
hl.workspace_rule({ workspace = "name:9", monitor = "DP-2" })
hl.workspace_rule({ workspace = "name:10", monitor = "DP-2" })
