include ./modern.conf

font_size        12
# font_family        JetBrainsMono Nerd Font Mono
font_family        Iosevka Nerd Font
bold_font          auto
italic_font        auto
bold_italic_font   auto

hide_window_decorations titlebar-only
window_padding_width 12

enable_audio_bell no

background_opacity         0.95
dynamic_background_opacity yes

confirm_os_window_close 0

# cursor_trail 1

modify_font cell_height 110%

action_alias ssh_kitten launch --type=overlay kitten ssh

disable_ligatures always
font_features "Iosevka Nerd Font" -liga +calt

map ctrl+equal change_font_size all +1.0
map ctrl+plus  change_font_size all +1.0

# Zoom out
map ctrl+minus change_font_size all -1.0

# Reset zoom
map ctrl+0 change_font_size all 0

map ctrl+backspace send_text all \x17 
