# Based on https://github.com/morhetz/gruvbox by morhetz <morhetz@gmail.com>
# Adapted to kitty by wdomitrz <witekdomitrz@gmail.com>

cursor                  #d9dbe8
cursor_text_color       background

url_color               #8091d6

visual_bell_color       #8ec07c
bell_border_color       #8ec07c

# active_border_color     #d3869b
# inactive_border_color   #665c54

foreground              #efefef
background              #050505
selection_foreground    #FEFEFE
selection_background    #6269ac

# active_tab_foreground   #fbf1c7
# active_tab_background   #665c54
# inactive_tab_foreground #a89984
# inactive_tab_background #3c3836

# black  (bg3/bg4)
color0                  #665c54
color8                  #7c6f64

# red
color1                  #e27878
color9                  #b04f4f

#: green
color2                  #63d454
color10                 #a6db9f

# yellow
color3                  #ebcd47
color11                 #e4d86c

# blue
color4                  #8aa2d6
color12                 #8accd6

# purple
color5                  #e0b2e0
color13                 #d3869b

# aqua
color6                  #a3d7ca
color14                 #a3d7ca

# white (fg4/fg3)
color7                  #dedede
color15                 #ffffff

