[triggers]
camera = "^cam$"
bookmarks = '^bk\s+(.*)$'
files = '^f\s+(.*)$'
clipboard = '^cp\s+(.*)$'
emojis = '^em\s+(.*)$'
shell = '^!\s+(.*)$'
lorem = '^lorem\s+(.*)$'
math = '^=\s*(.*)$'
dictionary = '^def\s+(.*)$'
system = '^sys\s+(.*)$'
color_picker = "^color$"
apps = '^app\s+(.*)$'
url = '^(https?://\S+|(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-]*[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}(?:[:/]\S*)?)$'
currency = '^fx\s+(.*)$'
note = "^note$"
ai = '^ \s+(.*)$'
time = '^time\s(.*)$'
settings = '^set\s*(.*)$'
timer = '^timer\s*(.*)$'
screenshots = '^ss\s*(.*)$'
shortcuts = '^q\s*(.*)$'
scripts = '^sc\s*(.*)$'

[theme]
background_color = "rgba(10, 10, 10, 1)"
background_opacity = 1.0
font_size = 15
font_color = "rgba(255, 255, 255, 1)"
font_family = "Inter"
monospace_font_family = "JetBrainsMono Nerd Font"
border_radius = 10
border_color = "rgba(255,255,255,0.35)"
border_thickness = 0
item_border_radius = 16
active_bg_color = "rgba(40, 40, 40, 1)"
active_border_color = "rgba(255,255,255,0.0)"

[window]
width = 900
height = 550

[[web_searches]]
name = "Google"
trigger = '^g\s+(.*)$'
url = "https://www.google.com/search?q={}"

[[web_searches]]
name = "YouTube"
trigger = '^yt\s+(.*)$'
url = "https://www.youtube.com/results?search_query={}"

[[web_searches]]
name = "GitHub"
trigger = '^gh\s+(.*)$'
url = "https://github.com/search?q={}"

[[web_searches]]
name = "Nix Packages"
trigger = '^nxp\s+(.*)$'
url = "https://search.nixos.org/packages?query={}"

[default_search]
web_searches = [
    "Google",
    "YouTube",
    "Nix Packages",
    "GitHub",
]
max_web_results = 1

[screenshots]
path = "~/Pictures/Screenshots"

[scripts]
path = "~/scripts"
