dynamic_background_opacity yes
font_family      JetBrainsMono Nerd Font
font_size 14

hide_window_decorations titlebar-only
window_padding_width 5

enable_audio_bell no

background_opacity         0.85
dynamic_background_opacity yes

cursor_trail 0
hide_window_decorations yes
window_padding_width 8

enable_audio_bell no
modify_font cell_height 110%

# Colors
include ./theme.conf
