# terminal opacity and blur
background_opacity .8

# terminal type
term xterm-256color

# terminal bell
enable_audio_bell no

# font
font_family           JetBrainsMono Nerd Font
text_antialiasing     false
disable_ligatures     always
text_autohint         true
font_size             14

# font size management 
map ctrl+shift+backspace change_font_size all 0

# cursor customization
cursor_shape block
cursor_blink_interval 1
cursor_stop_blinking_after 0
shell_integration no-cursor

# mouse
mouse_hide_wait -1

# window layout
window_padding_width 2
window_margin_width 2
hide_window_decorations yes

# black background with pretty accents
background            #000000
foreground            #D8DEE9
selection_foreground  #000000
selection_background  #EBCB8B

# normal colors
color0  #000000  
              # black
color1  #f54242  
              # red
color2  #6df266  
              # green
color3  #f2e666  
              # yellow
color4  #76bde3  
              # blue
color5  #eb7feb  
              # magenta
color6  #86e3c2  
              # cyan
color7  #E5E9F0  
              # white

# attach to tmux if running
map alt+shift+l send_text normal,application tmux attach || cd ~; tmux 
