# Simple Minimal Dark Theme for Kitty
background            #000000
foreground            #c5c8c6
selection_background  #373b41
selection_foreground  #ffffff

url_color             #8abeb7
cursor                #c5c8c6
cursor_text_color     #1e1e1e

# ANSI Colors
color0  #1d1f21
color1  #cc6666
color2  #b5bd68
color3  #f0c674
color4  #81a2be
color5  #b294bb
color6  #8abeb7
color7  #c5c8c6

# Bright Colors
color8  #666666
color9  #d54e53
color10 #b9ca4a
color11 #e7c547
color12 #7aa6da
color13 #c397d8
color14 #70c0ba
color15 #eaeaea

